# This config file is used to configure the client and specify the load on the server
# Available variables are:
# - server_address: 10.0.0.2
# - server_port: the port of the server to connect to
# - default_name: the default name to send to the server in this simple hello world example
# - total_requests: the number of requests to send to the server per iteration
# - max_concurrent_requests: the max. number of concurrent requests to send to the server in a single iteration
# - min_concurrent_requests: the min. number of concurrent requests to send to the server in a single iteration

server_address: localhost
server_port: 50051
default_name: world
total_requests: 1.000.000
max_concurrent_requests: 1000
min_concurrent_requests: 1
warmup_requests: 10000000
