# This config file is used to configure the server and specify the use of gRPC-intercepors
# Currently implemented interceptors are:
# - Logging Interceptor: logs the request and response of each gRPC call
# - Auth Interceptor: authenticates the user by checking mock token
# - Prometheus Metrics Interceptor: to do
# - Open Telemetry Interceptor: to do

# Logging Interceptor
logging:
  enabled: false

# Auth Interceptor
auth:
  enabled: false

# Prometheus Metrics Interceptor
metrics:
  enabled: false

# Open Telemetry Interceptor
telemetry:
  enable: true
