# This config file is used to configure the server and specify the use of gRPC-intercepors
# Currently implemented interceptors are:
# - Logging Interceptor: logs the request and response of each gRPC call
# - Auth Interceptor: authenticates the user by checking mock token
# - Prometheus Metrics Interceptor: to do
# - Open Telemetry Interceptor: to do

# Logging Interceptor
logging:
  enabled: true

# Auth Interceptor
# CAUTION: This is a mock auth interceptor, it is not secure and should not be used in production
# + it currently breaks the gRPC connection
auth:
  enabled: false

# Prometheus Metrics Interceptor
metrics:
  enabled: true

# Open Telemetry Interceptor
telemetry:
  enable: true
